[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "maya_mmd_tools"
version = "0.5.0"
description = "A set of tools for working with MMD data in Autodesk Maya."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/yohawing/maya_mmd_tools"
"Bug Tracker" = "https://github.com/yohawing/maya_mmd_tools/issues"

[project.optional-dependencies]
dev = [
    "flip-evaluator>=1.7,<2; python_version >= '3.8'",
]

[tool.setuptools.package-data]
mmd_tools = [
    "ui/assets/animator_toolset/*.png",
    "ui/assets/animator_toolset/*.svg",
    "ui/assets/morph_types/*.svg",
]

[tool.setuptools.packages.find]
include = ["mmd_tools*"]

[tool.ruff]
line-length = 128
indent-width = 4
target-version = "py310"
fix = true

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["E402"]
