# PySide2.QtCore type definitions
# Auto-generated stub file for PySide2.QtCore

from typing import Any, List, Optional, Union, Callable

class QObject:
    def __init__(self, parent: Optional['QObject'] = None) -> None: ...
    def parent(self) -> Optional['QObject']: ...
    def setParent(self, parent: Optional['QObject']) -> None: ...
    def children(self) -> List['QObject']: ...
    def findChild(self, type: type, name: str = "") -> Optional['QObject']: ...
    def findChildren(self, type: type, name: str = "") -> List['QObject']: ...
    def deleteLater(self) -> None: ...
    def destroyed: 'Signal'
    def connect(self, signal: 'Signal', slot: Callable) -> None: ...
    def disconnect(self, signal: 'Signal' = None, slot: Callable = None) -> None: ...

class Signal:
    def __init__(self, *types: type) -> None: ...
    def connect(self, slot: Callable) -> None: ...
    def disconnect(self, slot: Callable = None) -> None: ...
    def emit(self, *args: Any) -> None: ...

class Slot:
    def __init__(self, *types: type) -> Callable: ...

class QPoint:
    def __init__(self, x: int = 0, y: int = 0) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def __add__(self, other: 'QPoint') -> 'QPoint': ...
    def __sub__(self, other: 'QPoint') -> 'QPoint': ...

class QPointF:
    def __init__(self, x: float = 0.0, y: float = 0.0) -> None: ...
    def x(self) -> float: ...
    def y(self) -> float: ...
    def setX(self, x: float) -> None: ...
    def setY(self, y: float) -> None: ...
    def __add__(self, other: 'QPointF') -> 'QPointF': ...
    def __sub__(self, other: 'QPointF') -> 'QPointF': ...

class QSize:
    def __init__(self, width: int = 0, height: int = 0) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setWidth(self, width: int) -> None: ...
    def setHeight(self, height: int) -> None: ...
    def isEmpty(self) -> bool: ...
    def isValid(self) -> bool: ...

class QSizeF:
    def __init__(self, width: float = 0.0, height: float = 0.0) -> None: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def setWidth(self, width: float) -> None: ...
    def setHeight(self, height: float) -> None: ...
    def isEmpty(self) -> bool: ...
    def isValid(self) -> bool: ...

class QRect:
    def __init__(self, x: int = 0, y: int = 0, width: int = 0, height: int = 0) -> None: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setX(self, x: int) -> None: ...
    def setY(self, y: int) -> None: ...
    def setWidth(self, width: int) -> None: ...
    def setHeight(self, height: int) -> None: ...
    def topLeft(self) -> QPoint: ...
    def topRight(self) -> QPoint: ...
    def bottomLeft(self) -> QPoint: ...
    def bottomRight(self) -> QPoint: ...
    def center(self) -> QPoint: ...
    def isEmpty(self) -> bool: ...
    def isValid(self) -> bool: ...

class QRectF:
    def __init__(self, x: float = 0.0, y: float = 0.0, width: float = 0.0, height: float = 0.0) -> None: ...
    def x(self) -> float: ...
    def y(self) -> float: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    def setX(self, x: float) -> None: ...
    def setY(self, y: float) -> None: ...
    def setWidth(self, width: float) -> None: ...
    def setHeight(self, height: float) -> None: ...
    def topLeft(self) -> QPointF: ...
    def topRight(self) -> QPointF: ...
    def bottomLeft(self) -> QPointF: ...
    def bottomRight(self) -> QPointF: ...
    def center(self) -> QPointF: ...
    def isEmpty(self) -> bool: ...
    def isValid(self) -> bool: ...

class QString(str):
    def __init__(self, string: str = "") -> None: ...

class QByteArray:
    def __init__(self, data: Union[str, bytes] = b"") -> None: ...
    def data(self) -> bytes: ...
    def size(self) -> int: ...
    def isEmpty(self) -> bool: ...

class QTimer(QObject):
    timeout: Signal = ...
    
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def start(self, msec: int) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def setInterval(self, msec: int) -> None: ...
    def interval(self) -> int: ...
    def isActive(self) -> bool: ...
    def setSingleShot(self, singleShot: bool) -> None: ...
    def isSingleShot(self) -> bool: ...
    @staticmethod
    def singleShot(msec: int, slot: Callable) -> None: ...

class QThread(QObject):
    started: Signal = ...
    finished: Signal = ...
    
    def __init__(self, parent: Optional[QObject] = None) -> None: ...
    def start(self) -> None: ...
    def quit(self) -> None: ...
    def wait(self, time: int = -1) -> bool: ...
    def isRunning(self) -> bool: ...
    def isFinished(self) -> bool: ...
    def run(self) -> None: ...
    @staticmethod
    def currentThread() -> 'QThread': ...
    @staticmethod
    def sleep(secs: int) -> None: ...
    @staticmethod
    def msleep(msecs: int) -> None: ...
    @staticmethod
    def usleep(usecs: int) -> None: ...

class QUrl:
    def __init__(self, url: str = "") -> None: ...
    def toString(self) -> str: ...
    def setUrl(self, url: str) -> None: ...
    def scheme(self) -> str: ...
    def host(self) -> str: ...
    def port(self, defaultPort: int = -1) -> int: ...
    def path(self) -> str: ...
    def isValid(self) -> bool: ...
    def isEmpty(self) -> bool: ...

class QDir:
    def __init__(self, path: str = "") -> None: ...
    def exists(self) -> bool: ...
    def exists(self, name: str) -> bool: ...
    def path(self) -> str: ...
    def absolutePath(self) -> str: ...
    def canonicalPath(self) -> str: ...
    def dirName(self) -> str: ...
    def entryList(self, filters: List[str] = None, sort: int = 0) -> List[str]: ...
    def mkdir(self, dirName: str) -> bool: ...
    def mkpath(self, dirPath: str) -> bool: ...
    def remove(self, fileName: str) -> bool: ...
    def rmdir(self, dirName: str) -> bool: ...
    def rmpath(self, dirPath: str) -> bool: ...
    @staticmethod
    def currentPath() -> str: ...
    @staticmethod
    def homePath() -> str: ...
    @staticmethod
    def tempPath() -> str: ...

class QFile(QObject):
    def __init__(self, name: str = "", parent: Optional[QObject] = None) -> None: ...
    def open(self, mode: int) -> bool: ...
    def close(self) -> None: ...
    def read(self, maxlen: int = -1) -> QByteArray: ...
    def readAll(self) -> QByteArray: ...
    def write(self, data: Union[QByteArray, bytes, str]) -> int: ...
    def fileName(self) -> str: ...
    def setFileName(self, name: str) -> None: ...
    def exists(self) -> bool: ...
    def size(self) -> int: ...
    def isOpen(self) -> bool: ...
    def isReadable(self) -> bool: ...
    def isWritable(self) -> bool: ...
    @staticmethod
    def exists(fileName: str) -> bool: ...
    @staticmethod
    def remove(fileName: str) -> bool: ...

class QFileInfo:
    def __init__(self, file: Union[str, QFile]) -> None: ...
    def exists(self) -> bool: ...
    def fileName(self) -> str: ...
    def baseName(self) -> str: ...
    def completeSuffix(self) -> str: ...
    def suffix(self) -> str: ...
    def path(self) -> str: ...
    def absolutePath(self) -> str: ...
    def absoluteFilePath(self) -> str: ...
    def canonicalPath(self) -> str: ...
    def canonicalFilePath(self) -> str: ...
    def size(self) -> int: ...
    def isDir(self) -> bool: ...
    def isFile(self) -> bool: ...
    def isReadable(self) -> bool: ...
    def isWritable(self) -> bool: ...
    def isExecutable(self) -> bool: ...

class QVariant:
    def __init__(self, value: Any = None) -> None: ...
    def toBool(self) -> bool: ...
    def toInt(self) -> int: ...
    def toFloat(self) -> float: ...
    def toString(self) -> str: ...
    def toByteArray(self) -> QByteArray: ...
    def isValid(self) -> bool: ...
    def isNull(self) -> bool: ...
    def type(self) -> int: ...

class QSettings(QObject):
    def __init__(
        self,
        organization: str = "",
        application: str = "",
        parent: Optional[QObject] = None
    ) -> None: ...
    def setValue(self, key: str, value: Any) -> None: ...
    def value(self, key: str, defaultValue: Any = None) -> Any: ...
    def contains(self, key: str) -> bool: ...
    def remove(self, key: str) -> None: ...
    def clear(self) -> None: ...
    def beginGroup(self, prefix: str) -> None: ...
    def endGroup(self) -> None: ...
    def group(self) -> str: ...
    def allKeys(self) -> List[str]: ...
    def childKeys(self) -> List[str]: ...
    def childGroups(self) -> List[str]: ...

# Enums and constants
Qt_Horizontal: int = 1
Qt_Vertical: int = 2
Qt_LeftButton: int = 1
Qt_RightButton: int = 2
Qt_MiddleButton: int = 4