"""Smoke-test native mmd-anim export writer symbols from Python.

This script is intentionally small and Maya-independent. It verifies that the
loaded mmd-anim FFI DLL exposes the required PMX and typed VMD parts export
ABIs, then round-trips the generated bytes through the existing Python parser.
The legacy VMD JSON writer remains optional and is not used by the production
Bake Timeline route.
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
import tempfile
from pathlib import Path
from typing import List, Optional, Tuple

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from mmd_tools.core.native import (
    export_pmx_from_parts,
    export_vmd_from_parts,
    export_vmd_animation_json,
    get_mmd_runtime_library,
    is_native_json_export_available,
    is_native_pmx_parts_export_available,
    is_native_vmd_parts_export_available,
)
from mmd_tools.core.pmx_data import PmxData
from mmd_tools.core.vmd_data import VmdData


def _write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def _vmd_payload() -> dict:
    return {
        "kind": "vmd",
        "metadata": {
            "format": "vmd",
            "modelName": "native-export-smoke",
            "counts": {
                "bones": 1,
                "morphs": 0,
                "cameras": 0,
                "lights": 0,
                "selfShadows": 0,
                "properties": 0,
            },
            "maxFrame": 1,
        },
        "boneFrames": [
            {
                "boneName": "センター",
                "frame": 1,
                "translation": [1.0, 2.0, 3.0],
                "rotation": [0.0, 0.0, 0.0, 1.0],
                "interpolation": [20] * 64,
            }
        ],
        "morphFrames": [],
        "cameraFrames": [],
        "lightFrames": [],
        "selfShadowFrames": [],
        "propertyFrames": [],
    }


def _pmx_parts() -> Tuple[dict, List[float], List[float], List[float], List[int]]:
    descriptor = {
        "name": "native-export-smoke",
        "englishName": "native-export-smoke",
        "encoding": "utf-8",
        "materials": [{"name": "mat", "faceCount": 1}],
    }
    positions = [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0]
    normals = [0.0, 0.0, 1.0] * 3
    uvs = [0.0, 0.0, 1.0, 0.0, 0.0, 1.0]
    indices = [0, 1, 2]
    return descriptor, positions, normals, uvs, indices


def _vmd_parts() -> Tuple[dict, List[int], List[int], List[float], List[float], List[int], List[int], List[int], List[float]]:
    # Eight two-byte characters cross the 15-byte Bone-name boundary.  The
    # legacy writer emits the dangling lead byte; an empty raw field asks the
    # native writer to reproduce that exact byte-boundary truncation.
    bone_name = "あ" * 8
    morph_name = "笑い"
    interpolation = list(range(64))
    return (
        {
            "schema": "mmd-anim-vmd-parts",
            "version": 1,
            "modelName": "native-export-smoke",
            "modelNameBytes": list(b"native-export-smoke"),
            "boneNames": [{"name": bone_name, "nameBytes": []}],
            "morphNames": [{"name": morph_name, "nameBytes": list(morph_name.encode("cp932"))}],
            "cameraFrames": [],
            "lightFrames": [],
            "selfShadowFrames": [],
            "propertyFrames": [
                {
                    "frame": 3,
                    "visible": True,
                    "ikStates": [
                        {
                            "boneName": bone_name,
                            "boneNameBytes": list(bone_name.encode("cp932")),
                            "enabled": False,
                        }
                    ],
                }
            ],
        },
        [0],
        [1],
        [1.0, 2.0, 3.0],
        [0.0, 0.0, 0.0, 1.0],
        interpolation,
        [0],
        [2],
        [0.25],
    )


def _legacy_vmd_oracle_bytes() -> bytes:
    """Return the previous stream writer's exact bytes for ``_vmd_parts``."""

    def fixed(value: str, width: int) -> bytes:
        return value.encode("cp932")[:width].ljust(width, b"\0")

    bone_name = "あ" * 8
    payload = bytearray(b"Vocaloid Motion Data 0002\0\0\0\0\0")
    payload.extend(fixed("native-export-smoke", 20))
    payload.extend(struct.pack("<I", 1))
    payload.extend(fixed(bone_name, 15))
    payload.extend(struct.pack("<Ifffffff", 1, 1.0, 2.0, 3.0, 0.0, 0.0, 0.0, 1.0))
    payload.extend(bytes(range(64)))
    payload.extend(struct.pack("<I", 1))
    payload.extend(fixed("笑い", 15))
    payload.extend(struct.pack("<If", 2, 0.25))
    payload.extend(struct.pack("<III", 0, 0, 0))
    payload.extend(struct.pack("<IIBI", 1, 3, 1, 1))
    payload.extend(fixed(bone_name, 20))
    payload.extend(struct.pack("<B", 0))
    return bytes(payload)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true", help="fail when required native export symbols are missing")
    args = parser.parse_args(argv)

    lib = get_mmd_runtime_library()
    missing = []
    if lib is None:
        missing.append("mmd_runtime_library")
    if not is_native_pmx_parts_export_available():
        missing.append("pmx_parts_export")
    if not is_native_vmd_parts_export_available():
        missing.append("vmd_parts_export")

    if missing:
        print(json.dumps({"status": "skip", "missing": missing}, ensure_ascii=False))
        return 1 if args.strict else 0

    optional_json_exports = {"vmd": is_native_json_export_available("vmd")}
    skipped_optional = [
        f"{kind}_json_export"
        for kind, available in optional_json_exports.items()
        if not available
    ]

    with tempfile.TemporaryDirectory(prefix="native_export_smoke_") as tmp:
        tmp_dir = Path(tmp)

        (
            vmd_metadata,
            bone_name_indices,
            bone_frames,
            bone_translations,
            bone_rotations,
            bone_interpolations,
            morph_name_indices,
            morph_frames,
            morph_weights,
        ) = _vmd_parts()
        vmd_parts_bytes = export_vmd_from_parts(
            vmd_metadata,
            bone_name_indices,
            bone_frames,
            bone_translations,
            bone_rotations,
            bone_interpolations,
            morph_name_indices,
            morph_frames,
            morph_weights,
        )
        if not vmd_parts_bytes:
            raise RuntimeError("native VMD parts export returned empty bytes")
        vmd_parts_path = tmp_dir / "smoke-parts.vmd"
        _write(vmd_parts_path, vmd_parts_bytes)
        assert _legacy_vmd_oracle_bytes() == vmd_parts_bytes
        vmd_parts = VmdData().parse_file(str(vmd_parts_path))
        assert vmd_parts.header.model_name == "native-export-smoke"
        assert len(vmd_parts.bone_frames) == 1
        assert vmd_parts.bone_frames[0].bone_name == "あ" * 7 + "\ufffd"
        assert vmd_parts.bone_frames[0].frame_number == 1
        assert len(vmd_parts.morph_frames) == 1
        assert len(vmd_parts.ik_show_hide_frames) == 1

        if optional_json_exports["vmd"]:
            vmd_bytes = export_vmd_animation_json(_vmd_payload())
            if not vmd_bytes:
                raise RuntimeError("native VMD export returned empty bytes")
            vmd_path = tmp_dir / "smoke.vmd"
            _write(vmd_path, vmd_bytes)
            vmd = VmdData().parse_file(str(vmd_path))
            assert vmd.header.model_name == "native-export-smoke"
            assert len(vmd.bone_frames) == 1

        descriptor, positions, normals, uvs, indices = _pmx_parts()
        pmx_bytes = export_pmx_from_parts(descriptor, positions, normals, uvs, indices=indices)
        if not pmx_bytes:
            raise RuntimeError("native PMX parts export returned empty bytes")
        pmx_path = tmp_dir / "smoke.pmx"
        _write(pmx_path, pmx_bytes)
        pmx = PmxData().parse_file(str(pmx_path))
        assert pmx.header.model_name == "native-export-smoke"
        assert len(pmx.vertices) == 3

    print(json.dumps({"status": "pass", "skippedOptional": skipped_optional}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
