"""Smoke-test native mmd-anim export writer symbols from Python.

This script is intentionally small and Maya-independent. It verifies that the
loaded mmd-anim FFI DLL exposes the required PMX parts export ABI, then
round-trips the generated bytes through the existing Python parser. VMD JSON
writer ABI is optional because newer mmd-anim builds keep that writer
outside the C ABI; when present, this smoke still exercises them.
"""

from __future__ import annotations

import argparse
import json
import sys
import tempfile
from pathlib import Path
from typing import List, Optional, Tuple

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from mmd_tools.core.native import (
    export_pmx_from_parts,
    export_vmd_animation_json,
    get_mmd_runtime_library,
    is_native_json_export_available,
    is_native_pmx_parts_export_available,
)
from mmd_tools.core.pmx_data import PmxData
from mmd_tools.core.vmd_data import VmdData


def _write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def _vmd_payload() -> dict:
    return {
        "kind": "vmd",
        "metadata": {
            "format": "vmd",
            "modelName": "native-export-smoke",
            "counts": {
                "bones": 1,
                "morphs": 0,
                "cameras": 0,
                "lights": 0,
                "selfShadows": 0,
                "properties": 0,
            },
            "maxFrame": 1,
        },
        "boneFrames": [
            {
                "boneName": "センター",
                "frame": 1,
                "translation": [1.0, 2.0, 3.0],
                "rotation": [0.0, 0.0, 0.0, 1.0],
                "interpolation": [20] * 64,
            }
        ],
        "morphFrames": [],
        "cameraFrames": [],
        "lightFrames": [],
        "selfShadowFrames": [],
        "propertyFrames": [],
    }


def _pmx_parts() -> Tuple[dict, List[float], List[float], List[float], List[int]]:
    descriptor = {
        "name": "native-export-smoke",
        "englishName": "native-export-smoke",
        "encoding": "utf-8",
        "materials": [{"name": "mat", "faceCount": 1}],
    }
    positions = [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0]
    normals = [0.0, 0.0, 1.0] * 3
    uvs = [0.0, 0.0, 1.0, 0.0, 0.0, 1.0]
    indices = [0, 1, 2]
    return descriptor, positions, normals, uvs, indices


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true", help="fail when required native export symbols are missing")
    args = parser.parse_args(argv)

    lib = get_mmd_runtime_library()
    missing = []
    if lib is None:
        missing.append("mmd_runtime_library")
    if not is_native_pmx_parts_export_available():
        missing.append("pmx_parts_export")

    if missing:
        print(json.dumps({"status": "skip", "missing": missing}, ensure_ascii=False))
        return 1 if args.strict else 0

    optional_json_exports = {"vmd": is_native_json_export_available("vmd")}
    skipped_optional = [
        f"{kind}_json_export"
        for kind, available in optional_json_exports.items()
        if not available
    ]

    with tempfile.TemporaryDirectory(prefix="native_export_smoke_") as tmp:
        tmp_dir = Path(tmp)

        if optional_json_exports["vmd"]:
            vmd_bytes = export_vmd_animation_json(_vmd_payload())
            if not vmd_bytes:
                raise RuntimeError("native VMD export returned empty bytes")
            vmd_path = tmp_dir / "smoke.vmd"
            _write(vmd_path, vmd_bytes)
            vmd = VmdData().parse_file(str(vmd_path))
            assert vmd.header.model_name == "native-export-smoke"
            assert len(vmd.bone_frames) == 1

        descriptor, positions, normals, uvs, indices = _pmx_parts()
        pmx_bytes = export_pmx_from_parts(descriptor, positions, normals, uvs, indices=indices)
        if not pmx_bytes:
            raise RuntimeError("native PMX parts export returned empty bytes")
        pmx_path = tmp_dir / "smoke.pmx"
        _write(pmx_path, pmx_bytes)
        pmx = PmxData().parse_file(str(pmx_path))
        assert pmx.header.model_name == "native-export-smoke"
        assert len(pmx.vertices) == 3

    print(json.dumps({"status": "pass", "skippedOptional": skipped_optional}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
