# PySide2.QtGui type definitions
# Auto-generated stub file for PySide2.QtGui

from typing import Any, List, Optional, Union
from .QtCore import QObject, QPoint, QPointF, QSize, QSizeF, QRect, QRectF

class QPixmap:
    def __init__(
        self,
        width: int = 0,
        height: int = 0,
        fileName: Optional[str] = None
    ) -> None: ...
    def load(self, fileName: str) -> bool: ...
    def save(self, fileName: str, format: Optional[str] = None) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> QSize: ...
    def isNull(self) -> bool: ...
    def scaled(self, size: QSize, aspectRatioMode: int = 0, transformMode: int = 0) -> 'QPixmap': ...
    def scaled(self, width: int, height: int, aspectRatioMode: int = 0, transformMode: int = 0) -> 'QPixmap': ...

class QIcon:
    def __init__(self, pixmap: Optional[QPixmap] = None) -> None: ...
    def __init__(self, fileName: str) -> None: ...
    def pixmap(self, size: QSize) -> QPixmap: ...
    def pixmap(self, width: int, height: int) -> QPixmap: ...
    def addFile(self, fileName: str, size: QSize = QSize()) -> None: ...
    def addPixmap(self, pixmap: QPixmap) -> None: ...
    def isNull(self) -> bool: ...

class QFont:
    def __init__(self, family: str = "", pointSize: int = -1) -> None: ...
    def family(self) -> str: ...
    def setFamily(self, family: str) -> None: ...
    def pointSize(self) -> int: ...
    def setPointSize(self, pointSize: int) -> None: ...
    def pixelSize(self) -> int: ...
    def setPixelSize(self, pixelSize: int) -> None: ...
    def weight(self) -> int: ...
    def setWeight(self, weight: int) -> None: ...
    def bold(self) -> bool: ...
    def setBold(self, bold: bool) -> None: ...
    def italic(self) -> bool: ...
    def setItalic(self, italic: bool) -> None: ...
    def underline(self) -> bool: ...
    def setUnderline(self, underline: bool) -> None: ...

class QFontMetrics:
    def __init__(self, font: QFont) -> None: ...
    def width(self, text: str) -> int: ...
    def height(self) -> int: ...
    def ascent(self) -> int: ...
    def descent(self) -> int: ...
    def boundingRect(self, text: str) -> QRect: ...

class QColor:
    def __init__(
        self,
        red: int = 0,
        green: int = 0,
        blue: int = 0,
        alpha: int = 255
    ) -> None: ...
    def __init__(self, color: str) -> None: ...
    def red(self) -> int: ...
    def green(self) -> int: ...
    def blue(self) -> int: ...
    def alpha(self) -> int: ...
    def setRed(self, red: int) -> None: ...
    def setGreen(self, green: int) -> None: ...
    def setBlue(self, blue: int) -> None: ...
    def setAlpha(self, alpha: int) -> None: ...
    def setRgb(self, red: int, green: int, blue: int, alpha: int = 255) -> None: ...
    def getRgb(self) -> tuple[int, int, int, int]: ...
    def name(self) -> str: ...
    def setNamedColor(self, name: str) -> None: ...
    def isValid(self) -> bool: ...

class QPen:
    def __init__(self, color: QColor = QColor()) -> None: ...
    def __init__(self, style: int) -> None: ...
    def color(self) -> QColor: ...
    def setColor(self, color: QColor) -> None: ...
    def width(self) -> int: ...
    def setWidth(self, width: int) -> None: ...
    def style(self) -> int: ...
    def setStyle(self, style: int) -> None: ...

class QBrush:
    def __init__(self, color: QColor = QColor()) -> None: ...
    def __init__(self, style: int) -> None: ...
    def color(self) -> QColor: ...
    def setColor(self, color: QColor) -> None: ...
    def style(self) -> int: ...
    def setStyle(self, style: int) -> None: ...

class QPainter:
    def __init__(self, device: Optional['QPaintDevice'] = None) -> None: ...
    def begin(self, device: 'QPaintDevice') -> bool: ...
    def end(self) -> bool: ...
    def drawPoint(self, point: QPoint) -> None: ...
    def drawPoint(self, x: int, y: int) -> None: ...
    def drawLine(self, line: 'QLine') -> None: ...
    def drawLine(self, x1: int, y1: int, x2: int, y2: int) -> None: ...
    def drawRect(self, rect: QRect) -> None: ...
    def drawRect(self, x: int, y: int, width: int, height: int) -> None: ...
    def drawEllipse(self, rect: QRect) -> None: ...
    def drawEllipse(self, x: int, y: int, width: int, height: int) -> None: ...
    def drawText(self, point: QPoint, text: str) -> None: ...
    def drawText(self, x: int, y: int, text: str) -> None: ...
    def drawText(self, rect: QRect, flags: int, text: str) -> None: ...
    def drawPixmap(self, point: QPoint, pixmap: QPixmap) -> None: ...
    def drawPixmap(self, x: int, y: int, pixmap: QPixmap) -> None: ...
    def setPen(self, pen: QPen) -> None: ...
    def setPen(self, color: QColor) -> None: ...
    def setBrush(self, brush: QBrush) -> None: ...
    def setBrush(self, color: QColor) -> None: ...
    def setFont(self, font: QFont) -> None: ...
    def pen(self) -> QPen: ...
    def brush(self) -> QBrush: ...
    def font(self) -> QFont: ...

class QPaintDevice:
    def __init__(self) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def widthMM(self) -> int: ...
    def heightMM(self) -> int: ...

class QImage(QPaintDevice):
    def __init__(
        self,
        width: int = 0,
        height: int = 0,
        format: int = 0
    ) -> None: ...
    def __init__(self, fileName: str) -> None: ...
    def load(self, fileName: str) -> bool: ...
    def save(self, fileName: str, format: Optional[str] = None) -> bool: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def size(self) -> QSize: ...
    def isNull(self) -> bool: ...
    def pixel(self, x: int, y: int) -> int: ...
    def setPixel(self, x: int, y: int, color: int) -> None: ...
    def scaled(self, size: QSize, aspectRatioMode: int = 0, transformMode: int = 0) -> 'QImage': ...
    def scaled(self, width: int, height: int, aspectRatioMode: int = 0, transformMode: int = 0) -> 'QImage': ...

class QKeySequence:
    def __init__(self, key: Union[str, int] = 0) -> None: ...
    def toString(self) -> str: ...
    def matches(self, seq: 'QKeySequence') -> int: ...

class QAction(QObject):
    triggered: 'Signal' = ...
    toggled: 'Signal' = ...
    
    def __init__(self, text: str = "", parent: Optional[QObject] = None) -> None: ...
    def text(self) -> str: ...
    def setText(self, text: str) -> None: ...
    def icon(self) -> QIcon: ...
    def setIcon(self, icon: QIcon) -> None: ...
    def shortcut(self) -> QKeySequence: ...
    def setShortcut(self, shortcut: QKeySequence) -> None: ...
    def isEnabled(self) -> bool: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def trigger(self) -> None: ...

class QCursor:
    def __init__(self, shape: int = 0) -> None: ...
    def __init__(self, pixmap: QPixmap) -> None: ...
    def shape(self) -> int: ...
    def setShape(self, shape: int) -> None: ...
    def pos(self) -> QPoint: ...
    def setPos(self, x: int, y: int) -> None: ...
    def setPos(self, point: QPoint) -> None: ...

class QKeyEvent:
    def __init__(self, type: int, key: int, modifiers: int) -> None: ...
    def key(self) -> int: ...
    def modifiers(self) -> int: ...
    def text(self) -> str: ...
    def isAutoRepeat(self) -> bool: ...

class QMouseEvent:
    def __init__(self, type: int, pos: QPoint, button: int, buttons: int, modifiers: int) -> None: ...
    def pos(self) -> QPoint: ...
    def globalPos(self) -> QPoint: ...
    def x(self) -> int: ...
    def y(self) -> int: ...
    def button(self) -> int: ...
    def buttons(self) -> int: ...
    def modifiers(self) -> int: ...

# Constants
Qt_ArrowCursor: int = 0
Qt_UpArrowCursor: int = 1
Qt_CrossCursor: int = 2
Qt_WaitCursor: int = 3
Qt_IBeamCursor: int = 4
Qt_SizeVerCursor: int = 5
Qt_SizeHorCursor: int = 6