# PySide2.QtWidgets type definitions
# Auto-generated stub file for PySide2.QtWidgets

from typing import Any, List, Optional, Union, Callable
from .QtCore import QObject, Signal, QSize, QRect, QPoint
from .QtGui import QPixmap, QIcon, QFont

class QWidget(QObject):
    def __init__(self, parent: Optional['QWidget'] = None) -> None: ...
    def setWindowTitle(self, title: str) -> None: ...
    def setGeometry(self, x: int, y: int, width: int, height: int) -> None: ...
    def setGeometry(self, rect: QRect) -> None: ...
    def resize(self, width: int, height: int) -> None: ...
    def resize(self, size: QSize) -> None: ...
    def move(self, x: int, y: int) -> None: ...
    def move(self, point: QPoint) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def close(self) -> bool: ...
    def setVisible(self, visible: bool) -> None: ...
    def isVisible(self) -> bool: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setParent(self, parent: Optional['QWidget']) -> None: ...
    def parent(self) -> Optional['QWidget']: ...
    def setLayout(self, layout: 'QLayout') -> None: ...
    def layout(self) -> Optional['QLayout']: ...

class QMainWindow(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setCentralWidget(self, widget: QWidget) -> None: ...
    def centralWidget(self) -> Optional[QWidget]: ...
    def setMenuBar(self, menuBar: 'QMenuBar') -> None: ...
    def menuBar(self) -> 'QMenuBar': ...
    def setStatusBar(self, statusBar: 'QStatusBar') -> None: ...
    def statusBar(self) -> 'QStatusBar': ...

class QDialog(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def exec_(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...
    def done(self, result: int) -> None: ...

class QLabel(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setPixmap(self, pixmap: QPixmap) -> None: ...
    def pixmap(self) -> QPixmap: ...

class QPushButton(QWidget):
    clicked: Signal = ...
    
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: QIcon) -> None: ...
    def icon(self) -> QIcon: ...

class QLineEdit(QWidget):
    textChanged: Signal = ...
    returnPressed: Signal = ...
    
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setPlaceholderText(self, text: str) -> None: ...
    def placeholderText(self) -> str: ...

class QTextEdit(QWidget):
    textChanged: Signal = ...
    
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def setPlainText(self, text: str) -> None: ...
    def toPlainText(self) -> str: ...
    def setHtml(self, html: str) -> None: ...
    def toHtml(self) -> str: ...

class QCheckBox(QWidget):
    toggled: Signal = ...
    stateChanged: Signal = ...
    
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...

class QRadioButton(QWidget):
    toggled: Signal = ...
    
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...

class QComboBox(QWidget):
    currentTextChanged: Signal = ...
    currentIndexChanged: Signal = ...
    
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addItem(self, text: str, userData: Any = None) -> None: ...
    def addItems(self, texts: List[str]) -> None: ...
    def insertItem(self, index: int, text: str, userData: Any = None) -> None: ...
    def removeItem(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...
    def currentText(self) -> str: ...
    def currentIndex(self) -> int: ...
    def setCurrentText(self, text: str) -> None: ...
    def setCurrentIndex(self, index: int) -> None: ...

class QListWidget(QWidget):
    itemClicked: Signal = ...
    itemDoubleClicked: Signal = ...
    itemSelectionChanged: Signal = ...
    
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addItem(self, text: str) -> None: ...
    def addItems(self, texts: List[str]) -> None: ...
    def insertItem(self, row: int, text: str) -> None: ...
    def takeItem(self, row: int) -> Optional['QListWidgetItem']: ...
    def clear(self) -> None: ...
    def count(self) -> int: ...
    def currentItem(self) -> Optional['QListWidgetItem']: ...
    def currentRow(self) -> int: ...
    def setCurrentRow(self, row: int) -> None: ...

class QListWidgetItem:
    def __init__(self, text: str = "", parent: Optional[QListWidget] = None) -> None: ...
    def text(self) -> str: ...
    def setText(self, text: str) -> None: ...
    def data(self, role: int) -> Any: ...
    def setData(self, role: int, value: Any) -> None: ...

class QTreeWidget(QWidget):
    itemClicked: Signal = ...
    itemDoubleClicked: Signal = ...
    itemSelectionChanged: Signal = ...
    
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setHeaderLabels(self, labels: List[str]) -> None: ...
    def addTopLevelItem(self, item: 'QTreeWidgetItem') -> None: ...
    def takeTopLevelItem(self, index: int) -> Optional['QTreeWidgetItem']: ...
    def clear(self) -> None: ...
    def topLevelItemCount(self) -> int: ...
    def currentItem(self) -> Optional['QTreeWidgetItem']: ...

class QTreeWidgetItem:
    def __init__(self, parent: Optional[Union[QTreeWidget, 'QTreeWidgetItem']] = None) -> None: ...
    def setText(self, column: int, text: str) -> None: ...
    def text(self, column: int) -> str: ...
    def addChild(self, child: 'QTreeWidgetItem') -> None: ...
    def removeChild(self, child: 'QTreeWidgetItem') -> None: ...
    def childCount(self) -> int: ...
    def child(self, index: int) -> Optional['QTreeWidgetItem']: ...

# Layout classes
class QLayout(QObject):
    def __init__(self) -> None: ...
    def addWidget(self, widget: QWidget) -> None: ...
    def removeWidget(self, widget: QWidget) -> None: ...
    def setSpacing(self, spacing: int) -> None: ...
    def spacing(self) -> int: ...

class QBoxLayout(QLayout):
    def __init__(self, direction: int) -> None: ...
    def addWidget(self, widget: QWidget, stretch: int = 0) -> None: ...
    def addLayout(self, layout: QLayout, stretch: int = 0) -> None: ...
    def addStretch(self, stretch: int = 0) -> None: ...
    def insertWidget(self, index: int, widget: QWidget, stretch: int = 0) -> None: ...

class QVBoxLayout(QBoxLayout):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...

class QHBoxLayout(QBoxLayout):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...

class QGridLayout(QLayout):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addWidget(self, widget: QWidget, row: int, column: int, rowSpan: int = 1, columnSpan: int = 1) -> None: ...
    def addLayout(self, layout: QLayout, row: int, column: int, rowSpan: int = 1, columnSpan: int = 1) -> None: ...
    def setRowStretch(self, row: int, stretch: int) -> None: ...
    def setColumnStretch(self, column: int, stretch: int) -> None: ...

class QFormLayout(QLayout):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addRow(self, label: str, field: QWidget) -> None: ...
    def addRow(self, labelWidget: QWidget, field: QWidget) -> None: ...
    def addRow(self, widget: QWidget) -> None: ...

# Menu classes
class QMenuBar(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def addMenu(self, title: str) -> 'QMenu': ...
    def addMenu(self, menu: 'QMenu') -> 'QMenu': ...
    def addAction(self, text: str) -> 'QAction': ...

class QMenu(QWidget):
    def __init__(self, title: str = "", parent: Optional[QWidget] = None) -> None: ...
    def addAction(self, text: str) -> 'QAction': ...
    def addAction(self, action: 'QAction') -> 'QAction': ...
    def addSeparator(self) -> 'QAction': ...
    def addMenu(self, menu: 'QMenu') -> 'QMenu': ...

class QAction(QObject):
    triggered: Signal = ...
    
    def __init__(self, text: str = "", parent: Optional[QObject] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def text(self) -> str: ...
    def setIcon(self, icon: QIcon) -> None: ...
    def icon(self) -> QIcon: ...
    def setEnabled(self, enabled: bool) -> None: ...
    def isEnabled(self) -> bool: ...
    def setCheckable(self, checkable: bool) -> None: ...
    def isCheckable(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    def isChecked(self) -> bool: ...

class QStatusBar(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def showMessage(self, message: str, timeout: int = 0) -> None: ...
    def clearMessage(self) -> None: ...

class QProgressBar(QWidget):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setRange(self, minimum: int, maximum: int) -> None: ...
    def setMinimum(self, minimum: int) -> None: ...
    def minimum(self) -> int: ...
    def setMaximum(self, maximum: int) -> None: ...
    def maximum(self) -> int: ...

class QSlider(QWidget):
    valueChanged: Signal = ...
    
    def __init__(self, orientation: int = 1, parent: Optional[QWidget] = None) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setRange(self, minimum: int, maximum: int) -> None: ...
    def setMinimum(self, minimum: int) -> None: ...
    def minimum(self) -> int: ...
    def setMaximum(self, maximum: int) -> None: ...
    def maximum(self) -> int: ...

class QSpinBox(QWidget):
    valueChanged: Signal = ...
    
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setValue(self, value: int) -> None: ...
    def value(self) -> int: ...
    def setRange(self, minimum: int, maximum: int) -> None: ...
    def setMinimum(self, minimum: int) -> None: ...
    def minimum(self) -> int: ...
    def setMaximum(self, maximum: int) -> None: ...
    def maximum(self) -> int: ...

class QDoubleSpinBox(QWidget):
    valueChanged: Signal = ...
    
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    def setValue(self, value: float) -> None: ...
    def value(self) -> float: ...
    def setRange(self, minimum: float, maximum: float) -> None: ...
    def setMinimum(self, minimum: float) -> None: ...
    def minimum(self) -> float: ...
    def setMaximum(self, maximum: float) -> None: ...
    def maximum(self) -> float: ...
    def setDecimals(self, decimals: int) -> None: ...
    def decimals(self) -> int: ...

# File dialogs
class QFileDialog(QDialog):
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    @staticmethod
    def getOpenFileName(
        parent: Optional[QWidget] = None,
        caption: str = "",
        directory: str = "",
        filter: str = "",
    ) -> tuple[str, str]: ...
    @staticmethod
    def getSaveFileName(
        parent: Optional[QWidget] = None,
        caption: str = "",
        directory: str = "",
        filter: str = "",
    ) -> tuple[str, str]: ...
    @staticmethod
    def getExistingDirectory(
        parent: Optional[QWidget] = None,
        caption: str = "",
        directory: str = "",
    ) -> str: ...

# Message boxes
class QMessageBox(QDialog):
    Information: int = ...
    Warning: int = ...
    Critical: int = ...
    Question: int = ...
    
    def __init__(self, parent: Optional[QWidget] = None) -> None: ...
    @staticmethod
    def information(
        parent: Optional[QWidget],
        title: str,
        text: str,
    ) -> int: ...
    @staticmethod
    def warning(
        parent: Optional[QWidget],
        title: str,
        text: str,
    ) -> int: ...
    @staticmethod
    def critical(
        parent: Optional[QWidget],
        title: str,
        text: str,
    ) -> int: ...
    @staticmethod
    def question(
        parent: Optional[QWidget],
        title: str,
        text: str,
    ) -> int: ...

# Application
class QApplication(QObject):
    def __init__(self, args: List[str]) -> None: ...
    def exec_(self) -> int: ...
    def quit(self) -> None: ...
    @staticmethod
    def instance() -> Optional['QApplication']: ...
    @staticmethod
    def processEvents() -> None: ...