# Maya OpenMaya API type definitions
# Auto-generated stub file for maya.OpenMaya

from typing import Any, List, Optional, Tuple, Union, Iterator

# Basic types
class MObject:
    def __init__(self) -> None: ...
    def isNull(self) -> bool: ...
    def hasFn(self, functionSetType: int) -> bool: ...
    def apiType(self) -> int: ...

class MObjectHandle:
    def __init__(self, object: MObject) -> None: ...
    def object(self) -> MObject: ...
    def isValid(self) -> bool: ...
    def isAlive(self) -> bool: ...

class MDagPath:
    def __init__(self) -> None: ...
    def node(self) -> MObject: ...
    def transform(self) -> MObject: ...
    def fullPathName(self) -> str: ...
    def partialPathName(self) -> str: ...
    def isValid(self) -> bool: ...
    def hasFn(self, functionSetType: int) -> bool: ...
    def extendToShape(self) -> None: ...
    def pop(self, num: int = 1) -> None: ...
    def push(self, child: MObject) -> None: ...

class MSelectionList:
    def __init__(self) -> None: ...
    def add(self, item: Union[str, MObject, MDagPath]) -> None: ...
    def remove(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def length(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def getDependNode(self, index: int) -> MObject: ...
    def getDagPath(self, index: int) -> MDagPath: ...
    def getPlug(self, index: int) -> 'MPlug': ...

class MGlobal:
    @staticmethod
    def getSelectionListByName(name: str) -> MSelectionList: ...
    @staticmethod
    def getActiveSelectionList() -> MSelectionList: ...
    @staticmethod
    def setActiveSelectionList(selectionList: MSelectionList) -> None: ...
    @staticmethod
    def displayInfo(message: str) -> None: ...
    @staticmethod
    def displayWarning(message: str) -> None: ...
    @staticmethod
    def displayError(message: str) -> None: ...

# Vector and matrix types
class MVector:
    x: float
    y: float
    z: float
    
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    def __add__(self, other: 'MVector') -> 'MVector': ...
    def __sub__(self, other: 'MVector') -> 'MVector': ...
    def __mul__(self, scalar: float) -> 'MVector': ...
    def __rmul__(self, scalar: float) -> 'MVector': ...
    def length(self) -> float: ...
    def normal(self) -> 'MVector': ...
    def normalize(self) -> 'MVector': ...
    def dot(self, other: 'MVector') -> float: ...
    def cross(self, other: 'MVector') -> 'MVector': ...

class MPoint:
    x: float
    y: float
    z: float
    w: float
    
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 1.0) -> None: ...
    def __add__(self, vector: MVector) -> 'MPoint': ...
    def __sub__(self, other: 'MPoint') -> MVector: ...

class MMatrix:
    def __init__(self) -> None: ...
    def __getitem__(self, index: int) -> List[float]: ...
    def __setitem__(self, index: int, value: List[float]) -> None: ...
    @staticmethod
    def identity() -> 'MMatrix': ...
    def inverse(self) -> 'MMatrix': ...
    def transpose(self) -> 'MMatrix': ...
    def homogenize(self) -> 'MMatrix': ...

class MTransformationMatrix:
    def __init__(self, matrix: MMatrix = None) -> None: ...
    def asMatrix(self) -> MMatrix: ...
    def translation(self) -> MVector: ...
    def setTranslation(self, translation: MVector) -> None: ...
    def rotation(self) -> 'MEulerRotation': ...
    def setRotation(self, rotation: 'MEulerRotation') -> None: ...
    def scale(self) -> List[float]: ...
    def setScale(self, scale: List[float]) -> None: ...

class MEulerRotation:
    x: float
    y: float
    z: float
    order: int
    
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, order: int = 0) -> None: ...
    def asMatrix(self) -> MMatrix: ...
    def asQuaternion(self) -> 'MQuaternion': ...

class MQuaternion:
    x: float
    y: float
    z: float
    w: float
    
    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 1.0) -> None: ...
    def asMatrix(self) -> MMatrix: ...
    def asEulerRotation(self) -> MEulerRotation: ...

# Attribute and plug types
class MPlug:
    def __init__(self) -> None: ...
    def node(self) -> MObject: ...
    def attribute(self) -> MObject: ...
    def name(self) -> str: ...
    def partialName(self) -> str: ...
    def isNull(self) -> bool: ...
    def isConnected(self) -> bool: ...
    def isDestination(self) -> bool: ...
    def isSource(self) -> bool: ...
    def asBool(self) -> bool: ...
    def asInt(self) -> int: ...
    def asFloat(self) -> float: ...
    def asDouble(self) -> float: ...
    def asString(self) -> str: ...
    def asMObject(self) -> MObject: ...
    def setBool(self, value: bool) -> None: ...
    def setInt(self, value: int) -> None: ...
    def setFloat(self, value: float) -> None: ...
    def setDouble(self, value: float) -> None: ...
    def setString(self, value: str) -> None: ...
    def setMObject(self, value: MObject) -> None: ...
    def connectTo(self, other: 'MPlug', force: bool = False) -> None: ...
    def disconnectFromSource(self) -> None: ...
    def source(self) -> 'MPlug': ...
    def destinations(self) -> List['MPlug']: ...

class MAttribute:
    def __init__(self) -> None: ...

class MFnAttribute:
    def __init__(self, object: MObject = None) -> None: ...
    def name(self) -> str: ...
    def shortName(self) -> str: ...
    def isReadable(self) -> bool: ...
    def isWritable(self) -> bool: ...
    def isKeyable(self) -> bool: ...
    def isStorable(self) -> bool: ...
    def setReadable(self, readable: bool) -> None: ...
    def setWritable(self, writable: bool) -> None: ...
    def setKeyable(self, keyable: bool) -> None: ...
    def setStorable(self, storable: bool) -> None: ...

# Function sets
class MFnDependencyNode:
    def __init__(self, object: MObject = None) -> None: ...
    def setObject(self, object: MObject) -> MObject: ...
    def object(self) -> MObject: ...
    def name(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def typeName(self) -> str: ...
    def hasAttribute(self, name: str) -> bool: ...
    def attribute(self, name: str) -> MObject: ...
    def findPlug(self, attribute: Union[str, MObject], wantNetworkedPlug: bool = False) -> MPlug: ...
    def plugsAlias(self, attribute: MObject) -> str: ...

class MFnDagNode(MFnDependencyNode):
    def __init__(self, object: MObject = None) -> None: ...
    def fullPathName(self) -> str: ...
    def partialPathName(self) -> str: ...
    def parent(self, index: int) -> MObject: ...
    def parentCount(self) -> int: ...
    def child(self, index: int) -> MObject: ...
    def childCount(self) -> int: ...
    def getPath(self) -> MDagPath: ...
    def getAllPaths(self) -> List[MDagPath]: ...
    def isInstancedAttribute(self, attribute: MObject) -> bool: ...

class MFnTransform(MFnDagNode):
    def __init__(self, object: MObject = None) -> None: ...
    def transformation(self) -> MTransformationMatrix: ...
    def setTransformation(self, transform: MTransformationMatrix) -> None: ...
    def translation(self) -> MVector: ...
    def setTranslation(self, translation: MVector, space: int) -> None: ...
    def rotation(self) -> MEulerRotation: ...
    def setRotation(self, rotation: MEulerRotation, space: int = 0) -> None: ...
    def scale(self) -> List[float]: ...
    def setScale(self, scale: List[float]) -> None: ...

class MFnMesh(MFnDagNode):
    def __init__(self, object: MObject = None) -> None: ...
    def numVertices(self) -> int: ...
    def numPolygons(self) -> int: ...
    def numFaceVertices(self) -> int: ...
    def getPoints(self, space: int = 4) -> List[MPoint]: ...
    def setPoints(self, points: List[MPoint], space: int = 4) -> None: ...
    def getVertexNormals(self, angleWeighted: bool = True) -> List[MVector]: ...
    def setVertexNormals(self, normals: List[MVector]) -> None: ...
    def getUVs(self, uvSet: str = "") -> Tuple[List[float], List[float]]: ...
    def setUVs(self, uArray: List[float], vArray: List[float], uvSet: str = "") -> None: ...

# Iterator types
class MItDag:
    def __init__(self, filter: int = 256, root: MObject = None) -> None: ...
    def isDone(self) -> bool: ...
    def next(self) -> None: ...
    def currentItem(self) -> MObject: ...
    def getPath(self) -> MDagPath: ...
    def fullPathName(self) -> str: ...

class MItDependencyNodes:
    def __init__(self, filter: int = 256) -> None: ...
    def isDone(self) -> bool: ...
    def next(self) -> None: ...
    def thisNode(self) -> MObject: ...

class MItSelectionList:
    def __init__(self, selectionList: MSelectionList) -> None: ...
    def isDone(self) -> bool: ...
    def next(self) -> None: ...
    def getDependNode(self) -> MObject: ...
    def getDagPath(self) -> MDagPath: ...

# Constants and enums
kTransform: int
kMesh: int
kJoint: int
kSkinClusterFilter: int
kWorld: int
kObject: int
kComponent: int

# Utility functions
def MGlobal_getSelectionListByName(name: str) -> MSelectionList: ...
def MGlobal_getActiveSelectionList() -> MSelectionList: ...
def MGlobal_setActiveSelectionList(selectionList: MSelectionList) -> None: ...