# Maya OpenMaya API type definitions
# Auto-generated stub file for maya.OpenMaya

from typing import Any, List, Optional, Tuple, Union

# Basic types
class MObject:
    def __init__(self) -> None: ...
    def isNull(self) -> bool: ...
    def hasFn(self, functionSetType: int) -> bool: ...
    def apiType(self) -> int: ...

class MObjectHandle:
    def __init__(self, object: MObject) -> None: ...
    def object(self) -> MObject: ...
    def isValid(self) -> bool: ...
    def isAlive(self) -> bool: ...

class MDagPath:
    def __init__(self) -> None: ...
    def node(self) -> MObject: ...
    def transform(self) -> MObject: ...
    def fullPathName(self) -> str: ...
    def partialPathName(self) -> str: ...
    def isValid(self) -> bool: ...
    def hasFn(self, functionSetType: int) -> bool: ...
    def extendToShape(self) -> None: ...
    def pop(self, num: int = 1) -> None: ...
    def push(self, child: MObject) -> None: ...
    @staticmethod
    def getAPathTo(obj: MObject) -> "MDagPath": ...

class MSelectionList:
    def add(self, item: Union[str, MObject, MDagPath]) -> None: ...
    def remove(self, index: int) -> None: ...
    def clear(self) -> None: ...
    def length(self) -> int: ...
    def isEmpty(self) -> bool: ...
    def getDependNode(self, index: int) -> MObject: ...
    def getDagPath(self, index: int) -> MDagPath: ...
    def getPlug(self, index: int) -> "MPlug": ...
    def __init__(self, other: "MSelectionList" = None) -> None: ...

class MGlobal:
    @staticmethod
    def getSelectionListByName(name: str) -> MSelectionList: ...
    @staticmethod
    def getActiveSelectionList() -> MSelectionList: ...
    @staticmethod
    def setActiveSelectionList(selectionList: MSelectionList) -> None: ...
    @staticmethod
    def displayInfo(message: str) -> None: ...
    @staticmethod
    def displayWarning(message: str) -> None: ...
    @staticmethod
    def displayError(message: str) -> None: ...

# Vector and matrix types
class MVector:
    x: float
    y: float
    z: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...
    def __add__(self, other: "MVector") -> "MVector": ...
    def __sub__(self, other: "MVector") -> "MVector": ...
    def __mul__(self, scalar: float) -> "MVector": ...
    def __rmul__(self, scalar: float) -> "MVector": ...
    def length(self) -> float: ...
    def normal(self) -> "MVector": ...
    def normalize(self) -> "MVector": ...
    def dot(self, other: "MVector") -> float: ...
    def cross(self, other: "MVector") -> "MVector": ...

class MPoint:
    x: float
    y: float
    z: float
    w: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 1.0) -> None: ...
    def __add__(self, vector: MVector) -> "MPoint": ...
    def __sub__(self, other: "MPoint") -> MVector: ...

class MMatrix:
    def __init__(self) -> None: ...
    def __getitem__(self, index: int) -> List[float]: ...
    def __setitem__(self, index: int, value: List[float]) -> None: ...
    @staticmethod
    def identity() -> "MMatrix": ...
    def inverse(self) -> "MMatrix": ...
    def transpose(self) -> "MMatrix": ...
    def homogenize(self) -> "MMatrix": ...
    def setElement(self, row: int, col: int, value: float) -> None: ...

class MTransformationMatrix:
    def __init__(self, matrix: MMatrix = None) -> None: ...
    def asMatrix(self) -> MMatrix: ...
    def translation(self) -> MVector: ...
    def setTranslation(self, translation: MVector) -> None: ...
    def rotation(self, asQuaternion: bool = True) -> "MEulerRotation": ...
    def setRotation(self, rotation: "MEulerRotation") -> None: ...
    def scale(self) -> List[float]: ...
    def setScale(self, scale: List[float]) -> None: ...

class MEulerRotation:
    x: float
    y: float
    z: float
    order: int

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, order: int = 0) -> None: ...
    def asMatrix(self) -> MMatrix: ...
    def asQuaternion(self) -> "MQuaternion": ...

class MQuaternion:
    x: float
    y: float
    z: float
    w: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0, w: float = 1.0) -> None: ...
    def asMatrix(self) -> MMatrix: ...
    def asEulerRotation(self) -> MEulerRotation: ...

# Attribute and plug types
class MPlug:
    def __init__(self) -> None: ...
    def node(self) -> MObject: ...
    def attribute(self) -> MObject: ...
    def name(self) -> str: ...
    def partialName(self) -> str: ...
    isNull: bool
    isCompound: bool
    isArray: bool
    def isConnected(self) -> bool: ...
    def isDestination(self) -> bool: ...
    def isSource(self) -> bool: ...
    def asBool(self) -> bool: ...
    def asInt(self) -> int: ...
    def asFloat(self) -> float: ...
    def asDouble(self) -> float: ...
    def asString(self) -> str: ...
    def asMObject(self) -> MObject: ...
    def setBool(self, value: bool) -> None: ...
    def setInt(self, value: int) -> None: ...
    def setFloat(self, value: float) -> None: ...
    def setDouble(self, value: float) -> None: ...
    def setString(self, value: str) -> None: ...
    def setMObject(self, value: MObject) -> None: ...
    def connectTo(self, other: "MPlug", force: bool = False) -> None: ...
    def disconnectFromSource(self) -> None: ...
    def source(self) -> "MPlug": ...
    def destinations(self) -> List["MPlug"]: ...
    def child(self, index: int) -> "MPlug": ...
    def numChildren(self) -> int: ...
    def elementByLogicalIndex(self, index: int) -> "MPlug": ...
    # def numElements(self) -> int: ...
    numElements: int

class MAttribute:
    def __init__(self) -> None: ...

class MFnAttribute:
    def __init__(self, object: MObject = None) -> None: ...
    def name(self) -> str: ...
    def shortName(self) -> str: ...
    def isReadable(self) -> bool: ...
    def isWritable(self) -> bool: ...
    def isKeyable(self) -> bool: ...
    def isStorable(self) -> bool: ...
    def setReadable(self, readable: bool) -> None: ...
    def setWritable(self, writable: bool) -> None: ...
    def setKeyable(self, keyable: bool) -> None: ...
    def setStorable(self, storable: bool) -> None: ...

class MFnNumericData:
    kInvalid: int = 0
    kBoolean: int = 1
    kByte: int = 2
    kChar: int = 3
    kShort: int = 4
    kInt: int = 5
    kLong: int = 6
    kFloat: int = 7
    kDouble: int = 8
    k2Short: int = 9
    k2Int: int = 10
    k2Long: int = 11
    k2Float: int = 12
    k2Double: int = 13
    k3Short: int = 14
    k3Int: int = 15
    k3Long: int = 16
    k3Float: int = 17
    k3Double: int = 18
    k4Double: int = 19
    kAddr: int = 20
    kLast: int = 21

class MFnData:
    kInvalid: int = 0
    kNumeric: int = 1
    kPlugin: int = 2
    kPluginGeometry: int = 3
    kString: int = 4
    kMatrix: int = 5
    kStringArray: int = 6
    kDoubleArray: int = 7
    kFloatArray: int = 8
    kIntArray: int = 9
    kPointArray: int = 10
    kVectorArray: int = 11
    kComponentList: int = 12
    kMesh: int = 13
    kLattice: int = 14
    kNurbsCurve: int = 15
    kNurbsSurface: int = 16
    kSphere: int = 17
    kDynArrayAttrs: int = 18
    kDynSweptGeometry: int = 19
    kSubdSurface: int = 20
    kNObject: int = 21
    kNId: int = 22
    kAny: int = 23
    kFalloffFunction: int = 24
    kLast: int = 25

# Function sets
class MFnDependencyNode:
    def __init__(self, object: MObject = None) -> None: ...
    def setObject(self, object: MObject) -> MObject: ...
    def object(self) -> MObject: ...
    def name(self) -> str: ...
    def setName(self, name: str) -> None: ...
    def typeName(self) -> str: ...
    def hasAttribute(self, name: str) -> bool: ...
    def attribute(self, name: str) -> MObject: ...
    def findPlug(self, attribute: Union[str, MObject], wantNetworkedPlug: bool = False) -> MPlug: ...
    def plugsAlias(self, attribute: MObject) -> str: ...
    def addAttribute(self, attribute: MObject) -> None: ...

class MFnDagNode(MFnDependencyNode):
    def __init__(self, object: MObject = None) -> None: ...
    def fullPathName(self) -> str: ...
    def partialPathName(self) -> str: ...
    def parent(self, index: int) -> MObject: ...
    def parentCount(self) -> int: ...
    def child(self, index: int) -> MObject: ...
    def childCount(self) -> int: ...
    def getPath(self) -> MDagPath: ...
    def getAllPaths(self) -> List[MDagPath]: ...
    def isInstancedAttribute(self, attribute: MObject) -> bool: ...

class MFnTransform(MFnDagNode):
    def __init__(self, object: MObject = None) -> None: ...
    def transformation(self) -> MTransformationMatrix: ...
    def setTransformation(self, transform: MTransformationMatrix) -> None: ...
    def translation(self) -> MVector: ...
    def setTranslation(self, translation: MVector, space: int) -> None: ...
    def rotation(self) -> MEulerRotation: ...
    def setRotation(self, rotation: MEulerRotation, space: int = 0) -> None: ...
    def scale(self) -> List[float]: ...
    def setScale(self, scale: List[float]) -> None: ...

class MFnMesh(MFnDagNode):
    def __init__(self, object: Union[MObject, MDagPath] = None) -> None: ...
    @property
    def numVertices(self) -> int: ...
    @property
    def numPolygons(self) -> int: ...
    @property
    def numFaceVertices(self) -> int: ...
    def getPoints(self, space: int = 4) -> List[MPoint]: ...
    def setPoints(self, points: List[MPoint], space: int = 4) -> None: ...
    def getVertexNormals(self, angleWeighted: bool = True) -> List[MVector]: ...
    def setVertexNormals(self, normals: List[MVector]) -> None: ...
    def getUVs(self, uvSet: str = "") -> Tuple[List[float], List[float]]: ...
    def setUVs(self, uArray: "MFloatArray", vArray: "MFloatArray", uvSet: str = "") -> None: ...
    def create(
        self, points: "MPointArray", polygonCounts: "MIntArray", polygonConnects: "MIntArray", parent: MDagPath = None
    ) -> MObject: ...
    def createUVSet(self, uvSetName: str) -> None: ...
    def assignUVs(self, polygonCounts: "MIntArray", uvIds: "MIntArray", uvSet: str = "") -> None: ...

class MDoubleArray:
    def __init__(self, arg1: Union[int, List[float], None] = None, initialValue: float = 0.0) -> None: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __getitem__(self, index: int) -> float: ...
    def __len__(self) -> int: ...
    def append(self, value: float) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> "MDoubleArray": ...
    def insert(self, index: int, value: float) -> None: ...
    def remove(self, index: int) -> None: ...
    def set(self, value: float, index: int) -> None: ...

class MIntArray:
    def __init__(self, arg1: Union[int, List[int], None] = None, initialValue: int = 0) -> None: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def __getitem__(self, index: int) -> int: ...
    def __len__(self) -> int: ...
    def append(self, value: int) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> "MIntArray": ...
    def insert(self, index: int, value: int) -> None: ...
    def remove(self, index: int) -> None: ...
    def set(self, value: int, index: int) -> None: ...

class MFloatArray:
    def __init__(self, arg1: Union[int, List[float], None] = None, initialValue: float = 0.0) -> None: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __getitem__(self, index: int) -> float: ...
    def __len__(self) -> int: ...
    def append(self, value: float) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> "MFloatArray": ...
    def insert(self, index: int, value: float) -> None: ...
    def remove(self, index: int) -> None: ...
    def set(self, value: float, index: int) -> None: ...

class MPointArray:
    def __init__(self) -> None: ...
    def append(self, p: "MPoint") -> None: ...

class MFnNumericAttribute:
    def __init__(self, object: MObject = None) -> None: ...
    def create(self, longName: str, shortName: str, dataType: int) -> MObject: ...
    def numericType(self) -> int: ...

class MFnTypedAttribute:
    def __init__(self, object: MObject = None) -> None: ...
    def create(self, longName: str, shortName: str, dataType: int) -> MObject: ...
    def attrType(self) -> int: ...

class MFnDoubleArrayData:
    def __init__(self) -> None: ...
    def create(self) -> MObject: ...
    def set(self, arr: MDoubleArray) -> None: ...

class MFnIntArrayData:
    def __init__(self) -> None: ...
    def create(self) -> MObject: ...
    def set(self, arr: MIntArray) -> None: ...

class MFnSingleIndexedComponent:
    def __init__(self) -> None: ...
    def create(self, compType: int) -> MObject: ...
    def addElements(self, elements: List[int]) -> None: ...

class MTime:
    def __init__(self, value: float = 0.0, unit: int = 0) -> None: ...
    @staticmethod
    def uiUnit() -> int: ...

# Additional constants used by maya_utils
kBlendShape: int
kCamera: int
kDirectionalLight: int
kMeshVertComponent: int

# Iterator types
class MItDag:
    kDepthFirst: int = 0
    kBreadthFirst: int = 1

    def __init__(self, traversalType: int = 256, filterType: int = None) -> None: ...
    def isDone(self) -> bool: ...
    def next(self) -> None: ...
    def currentItem(self) -> MObject: ...
    def getPath(self) -> MDagPath: ...
    def fullPathName(self) -> str: ...

class MItDependencyNodes:
    def __init__(self, filter: int = 256) -> None: ...
    def isDone(self) -> bool: ...
    def next(self) -> None: ...
    def thisNode(self) -> MObject: ...

class MItSelectionList:
    def __init__(self, selectionList: MSelectionList) -> None: ...
    def isDone(self) -> bool: ...
    def next(self) -> None: ...
    def getDependNode(self) -> MObject: ...
    def getDagPath(self) -> MDagPath: ...

# Constants and enums
kTransform: int
kMesh: int
kJoint: int
kSkinClusterFilter: int
kWorld: int
kObject: int
kComponent: int

# MFn constants
class MFn:
    kInvalid: int = 0
    kBase: int = 1
    kNamedObject: int = 2
    kDependencyNode: int = 3
    kDagNode: int = 4
    kTransform: int = 5
    kShape: int = 6
    kGeometry: int = 7
    kMesh: int = 8
    kNurbsCurve: int = 9
    kNurbsSurface: int = 10
    kJoint: int = 11
    kCamera: int = 12
    kLight: int = 13
    kDirectionalLight: int = 14
    kPointLight: int = 15
    kSpotLight: int = 16
    kAreaLight: int = 17
    kBlendShape: int = 18
    kSkinCluster: int = 19
    kCluster: int = 20
    kConstraint: int = 21
    kNumericAttribute: int = 22
    kTypedAttribute: int = 23
    kStringData: int = 24
    kDoubleArrayData: int = 25
    kIntArrayData: int = 26
    kMeshVertComponent: int = 27
    kMeshEdgeComponent: int = 28
    kMeshFaceComponent: int = 29

# Modifier classes
class MDGModifier:
    def __init__(self) -> None: ...
    def createNode(self, typeName: str) -> MObject: ...
    def deleteNode(self, node: MObject) -> None: ...
    def renameNode(self, node: MObject, newName: str) -> None: ...
    def connect(self, source: MPlug, dest: MPlug) -> None: ...
    def disconnect(self, source: MPlug, dest: MPlug) -> None: ...
    def newPlugValue(self, plug: MPlug, value: Any) -> None: ...
    def newPlugValueBool(self, plug: MPlug, value: bool) -> None: ...
    def newPlugValueChar(self, plug: MPlug, value: str) -> None: ...
    def newPlugValueDouble(self, plug: MPlug, value: float) -> None: ...
    def newPlugValueFloat(self, plug: MPlug, value: float) -> None: ...
    def newPlugValueInt(self, plug: MPlug, value: int) -> None: ...
    def newPlugValueShort(self, plug: MPlug, value: int) -> None: ...
    def newPlugValueString(self, plug: MPlug, value: str) -> None: ...
    def addAttribute(self, node: MObject, attribute: MObject) -> None: ...
    def removeAttribute(self, node: MObject, attribute: MObject) -> None: ...
    def doIt(self) -> None: ...
    def undoIt(self) -> None: ...

class MDagModifier(MDGModifier):
    def __init__(self) -> None: ...
    def createNode(self, typeName: str, parent: MObject = MObject()) -> MObject: ...
    def reparentNode(self, node: MObject, newParent: MObject = MObject()) -> None: ...

# Utility functions (class-based array types and helpers are declared above)
