# Maya API 2.0 OpenMayaAnim type definitions
# Auto-generated stub file for maya.api.OpenMayaAnim

from typing import Any, List, Tuple, overload, Optional
from .OpenMaya import MObject, MPlug, MDagPath, MTime, MVector, MDoubleArray, MIntArray

# Animation curve types and constants
class MFnAnimCurve:
    # Tangent types
    kTangentGlobal: int = 0
    kTangentFixed: int = 1
    kTangentLinear: int = 2
    kTangentFlat: int = 3
    kTangentSmooth: int = 4
    kTangentStep: int = 5
    kTangentStepNext: int = 6
    kTangentSlow: int = 7
    kTangentFast: int = 8
    kTangentClamped: int = 9
    kTangentPlateau: int = 10
    kTangentAuto: int = 11

    # Infinity types
    kConstant: int = 0
    kLinear: int = 1
    kCycle: int = 2
    kCycleRelative: int = 3
    kOscillate: int = 4

    # Animation curve types
    kAnimCurveTA: int = 0  # Time to Angular
    kAnimCurveTL: int = 1  # Time to Linear
    kAnimCurveTT: int = 2  # Time to Time
    kAnimCurveTU: int = 3  # Time to Unitless
    kAnimCurveUA: int = 4  # Unitless to Angular
    kAnimCurveUL: int = 5  # Unitless to Linear
    kAnimCurveUT: int = 6  # Unitless to Time
    kAnimCurveUU: int = 7  # Unitless to Unitless
    kAnimCurveUnknown: int = 8

    def __init__(self, object: MObject = None) -> None: ...
    @overload
    def create(self, node: MObject, attribute: MObject, modifier: Optional["MDGModifier"] = ...) -> MObject: ...
    @overload
    def create(
        self, plug: MPlug, animCurveType: int = kAnimCurveUnknown, modifier: Optional["MDGModifier"] = ...
    ) -> MObject: ...
    # def create(self, *args: Any, **kwargs: Any) -> MObject: ...
    # Key management
    def addKey(
        self,
        time: MTime,
        value: float,
        tangentInType: int = kTangentLinear,
        tangentOutType: int = kTangentLinear,
        change: "MAnimCurveChange" = None,
    ) -> int: ...
    def addKeyframe(self, time: MTime, value: float, change: "MAnimCurveChange" = None) -> int: ...
    def remove(self, index: int, change: "MAnimCurveChange" = None) -> None: ...
    def setValue(self, index: int, value: float, change: "MAnimCurveChange" = None) -> None: ...
    def setTime(self, index: int, time: MTime, change: "MAnimCurveChange" = None) -> None: ...

    # Key queries
    def numKeys(self) -> int: ...
    def input(self, index: int) -> MTime: ...
    def value(self, index: int) -> float: ...
    def time(self, index: int) -> MTime: ...
    def findClosest(self, time: MTime) -> int: ...
    def find(self, time: MTime) -> int: ...

    # Evaluation
    def evaluate(self, time: MTime) -> float: ...
    def evaluateDerivative(self, time: MTime) -> float: ...

    # Tangent management
    def inTangentType(self, index: int) -> int: ...
    def outTangentType(self, index: int) -> int: ...
    def setInTangentType(self, index: int, tangentType: int, change: "MAnimCurveChange" = None) -> None: ...
    def setOutTangentType(self, index: int, tangentType: int, change: "MAnimCurveChange" = None) -> None: ...
    def getTangent(self, index: int, inTangent: bool = True) -> Tuple[float, float]: ...
    def setTangent(self, index: int, x: float, y: float, inTangent: bool = True, change: "MAnimCurveChange" = None) -> None: ...

    # Weight management
    def weightsLocked(self, index: int) -> bool: ...
    def setWeightsLocked(self, index: int, locked: bool, change: "MAnimCurveChange" = None) -> None: ...
    def inWeight(self, index: int) -> float: ...
    def outWeight(self, index: int) -> float: ...
    def setWeight(self, index: int, weight: float, inWeight: bool = True, change: "MAnimCurveChange" = None) -> None: ...

    # Curve properties
    def animCurveType(self) -> int: ...
    def isWeighted(self) -> bool: ...
    def setIsWeighted(self, weighted: bool, change: "MAnimCurveChange" = None) -> None: ...
    def preInfinityType(self) -> int: ...
    def postInfinityType(self) -> int: ...
    def setPreInfinityType(self, infinityType: int, change: "MAnimCurveChange" = None) -> None: ...
    def setPostInfinityType(self, infinityType: int, change: "MAnimCurveChange" = None) -> None: ...

    # Utility methods
    def isStatic(self) -> bool: ...
    def isUnitlessInput(self) -> bool: ...
    def timedAnimCurveTypeForPlug(self, plug: MPlug) -> int: ...
    def unitlessAnimCurveTypeForPlug(self, plug: MPlug) -> int: ...

class MAnimCurveChange:
    def __init__(self) -> None: ...
    def redoIt(self) -> None: ...
    def undoIt(self) -> None: ...

# Skin cluster functionality
class MFnSkinCluster:
    def __init__(self, object: MObject = None) -> None: ...

    # Influence objects
    def influenceObjects(self) -> List[MDagPath]: ...
    def numInfluenceObjects(self) -> int: ...
    def indexForInfluenceObject(self, path: MDagPath) -> int: ...
    def influenceObjectAtIndex(self, index: int) -> MDagPath: ...
    def addInfluenceObject(self, path: MDagPath, index: int = -1) -> int: ...
    def removeInfluenceObject(self, path: MDagPath) -> None: ...

    # Weight management
    def getWeights(self, dagPath: MDagPath, component: MObject, influences: MIntArray = None) -> MDoubleArray: ...
    def setWeights(
        self,
        dagPath: MDagPath,
        component: MObject,
        influences: MIntArray,
        weights: MDoubleArray,
        normalize: bool = True,
        returnOldWeights: MDoubleArray = None,
    ) -> None: ...
    def getBlendWeights(self, dagPath: MDagPath, component: MObject) -> MDoubleArray: ...
    def setBlendWeights(self, dagPath: MDagPath, component: MObject, weights: MDoubleArray) -> None: ...

    # Utilities
    def getPointsAffectedByInfluence(self, path: MDagPath, dagPath: MDagPath, component: MObject) -> None: ...
    def skinningMethod(self) -> int: ...
    def setSkinningMethod(self, method: int) -> None: ...
    def normalizeWeights(self) -> bool: ...
    def setNormalizeWeights(self, normalize: bool) -> None: ...
    def deformerSet(self) -> MObject: ...

# Blend shape functionality
class MFnBlendShapeDeformer:
    def __init__(self, object: MObject = None) -> None: ...

    # Target management
    def addBaseObject(self, object: MObject) -> int: ...
    def removeBaseObject(self, index: int) -> None: ...
    def baseObjects(self) -> List[MObject]: ...
    def numBaseObjects(self) -> int: ...
    def indexForBaseObject(self, object: MObject) -> int: ...
    def baseObjectAtIndex(self, index: int) -> MObject: ...

    # Target shapes
    def addTarget(self, baseIndex: int, targetIndex: int, target: MObject, weight: float = 1.0) -> None: ...
    def removeTarget(self, baseIndex: int, targetIndex: int) -> None: ...
    def targetItemCount(self, baseIndex: int) -> int: ...
    def targetItems(self, baseIndex: int) -> List[int]: ...
    def targetItemAtIndex(self, baseIndex: int, targetItemIndex: int) -> int: ...
    def targetAtIndex(self, baseIndex: int, targetIndex: int) -> MObject: ...

    # Weight management
    def weight(self, baseIndex: int, targetIndex: int) -> float: ...
    def setWeight(self, baseIndex: int, targetIndex: int, weight: float) -> None: ...
    def weightAtIndex(self, targetItemIndex: int) -> float: ...
    def setWeightAtIndex(self, targetItemIndex: int, weight: float) -> None: ...

    # Utilities
    def envelope(self) -> float: ...
    def setEnvelope(self, envelope: float) -> None: ...
    def origin(self) -> int: ...
    def setOrigin(self, origin: int) -> None: ...

# Key management
class MAnimMessage:
    @staticmethod
    def addAnimKeyframeEditedCallback(func: callable, clientData: Any = None) -> int: ...
    @staticmethod
    def addAnimCurveEditedCallback(func: callable, clientData: Any = None) -> int: ...
    @staticmethod
    def addDisableImplicitControlCallback(func: callable, clientData: Any = None) -> int: ...
    @staticmethod
    def flushAnimKeyframeEditedCallbacks() -> None: ...

# Time utilities
class MAnimControl:
    @staticmethod
    def currentTime() -> MTime: ...
    @staticmethod
    def setCurrentTime(time: MTime) -> None: ...
    @staticmethod
    def minTime() -> MTime: ...
    @staticmethod
    def maxTime() -> MTime: ...
    @staticmethod
    def setMinTime(time: MTime) -> None: ...
    @staticmethod
    def setMaxTime(time: MTime) -> None: ...
    @staticmethod
    def animationStartTime() -> MTime: ...
    @staticmethod
    def animationEndTime() -> MTime: ...
    @staticmethod
    def setAnimationStartEndTime(start: MTime, end: MTime) -> None: ...
    @staticmethod
    def playbackMode() -> int: ...
    @staticmethod
    def setPlaybackMode(mode: int) -> None: ...
    @staticmethod
    def playForward() -> None: ...
    @staticmethod
    def playBackward() -> None: ...
    @staticmethod
    def stop() -> None: ...
    @staticmethod
    def isPlaying() -> bool: ...
    @staticmethod
    def isScrubbing() -> bool: ...
    @staticmethod
    def globalInTangentType() -> int: ...
    @staticmethod
    def globalOutTangentType() -> int: ...
    @staticmethod
    def setGlobalInTangentType(tangentType: int) -> None: ...
    @staticmethod
    def setGlobalOutTangentType(tangentType: int) -> None: ...
    @staticmethod
    def weightedTangents() -> bool: ...
    @staticmethod
    def setWeightedTangents(weighted: bool) -> None: ...

# Animation utilities
class MAnimUtil:
    @staticmethod
    def findAnimatedPlugs(node: MObject, checkParent: bool = False) -> List[MPlug]: ...
    @staticmethod
    def findAnimatedPlugs(dagPath: MDagPath, checkParent: bool = False) -> List[MPlug]: ...
    @staticmethod
    def findAnimation(plug: MPlug) -> MObject: ...
    @staticmethod
    def findSetDrivenKeyAnimation(plug: MPlug) -> MObject: ...
    @staticmethod
    def isAnimated(plug: MPlug, checkParent: bool = False) -> bool: ...
    @staticmethod
    def isAnimated(node: MObject, checkParent: bool = False) -> bool: ...
    @staticmethod
    def isAnimated(dagPath: MDagPath, checkParent: bool = False) -> bool: ...

# Keyframe utilities
class MKeyframe:
    def __init__(self) -> None: ...
    def time(self) -> MTime: ...
    def setTime(self, time: MTime) -> None: ...
    def value(self) -> float: ...
    def setValue(self, value: float) -> None: ...
    def inTangentType(self) -> int: ...
    def setInTangentType(self, tangentType: int) -> None: ...
    def outTangentType(self) -> int: ...
    def setOutTangentType(self, tangentType: int) -> None: ...
    def inTangentAngle(self) -> float: ...
    def setInTangentAngle(self, angle: float) -> None: ...
    def outTangentAngle(self) -> float: ...
    def setOutTangentAngle(self, angle: float) -> None: ...
    def inWeight(self) -> float: ...
    def setInWeight(self, weight: float) -> None: ...
    def outWeight(self) -> float: ...
    def setOutWeight(self, weight: float) -> None: ...

# IK functionality
class MFnIkSolver:
    def __init__(self, object: MObject = None) -> None: ...
    def solverType(self) -> str: ...
    def maxIterations(self) -> int: ...
    def setMaxIterations(self, maxIterations: int) -> None: ...
    def tolerance(self) -> float: ...
    def setTolerance(self, tolerance: float) -> None: ...

class MFnIkHandle:
    def __init__(self, object: MObject = None) -> None: ...
    def create(self, startJoint: MDagPath, endEffector: MDagPath, solver: MObject = None) -> MObject: ...
    def solver(self) -> MObject: ...
    def setSolver(self, solver: MObject) -> None: ...
    def startJoint(self) -> MDagPath: ...
    def endEffector(self) -> MDagPath: ...
    def priority(self) -> int: ...
    def setPriority(self, priority: int) -> None: ...
    def weight(self) -> float: ...
    def setWeight(self, weight: float) -> None: ...
    def snapEnable(self) -> bool: ...
    def setSnapEnable(self, enable: bool) -> None: ...
    def stickyEnable(self) -> bool: ...
    def setStickyEnable(self, enable: bool) -> None: ...
    def poleVectorX(self) -> float: ...
    def poleVectorY(self) -> float: ...
    def poleVectorZ(self) -> float: ...
    def setPoleVector(self, x: float, y: float, z: float) -> None: ...

class MFnIkEffector:
    def __init__(self, object: MObject = None) -> None: ...
    def create(self, joint: MDagPath) -> MObject: ...

class MFnIkJoint:
    def __init__(self, object: MObject = None) -> None: ...

# Character set functionality
class MFnCharacter:
    def __init__(self, object: MObject = None) -> None: ...
    def create(self) -> MObject: ...
    def addCurveToClip(self, curve: MObject, sourceClip: MObject, index: int = -1) -> int: ...
    def removeCurveFromClip(self, curve: MObject, sourceClip: MObject) -> None: ...
    def getSourceClipPlugs(self, sourceClip: MObject) -> List[MPlug]: ...
    def attachSourceToCharacter(self, sourceClip: MObject, character: MObject) -> None: ...
    def attachInstanceToCharacter(self, instanceClip: MObject, character: MObject) -> None: ...

# Motion path functionality
class MFnMotionPath:
    def __init__(self, object: MObject = None) -> None: ...
    def create(
        self, pathObject: MObject, timeStart: float = 0.0, timeEnd: float = 1.0, constrainedObject: MObject = None
    ) -> MObject: ...
    def pathObject(self) -> MObject: ...
    def setPathObject(self, pathObject: MObject) -> None: ...
    def uStart(self) -> float: ...
    def setUStart(self, start: float) -> None: ...
    def uEnd(self) -> float: ...
    def setUEnd(self, end: float) -> None: ...
    def follow(self) -> bool: ...
    def setFollow(self, follow: bool) -> None: ...
    def followAxis(self) -> int: ...
    def setFollowAxis(self, axis: int) -> None: ...
    def upAxis(self) -> int: ...
    def setUpAxis(self, axis: int) -> None: ...
    def worldUpType(self) -> int: ...
    def setWorldUpType(self, upType: int) -> None: ...
    def worldUpVector(self) -> MVector: ...
    def setWorldUpVector(self, vector: MVector) -> None: ...
    def bank(self) -> bool: ...
    def setBank(self, bank: bool) -> None: ...
    def bankScale(self) -> float: ...
    def setBankScale(self, scale: float) -> None: ...
    def bankThreshold(self) -> float: ...
    def setBankThreshold(self, threshold: float) -> None: ...

# Constants for various enums
kPlaybackOnce: int = 0
kPlaybackLoop: int = 1
kPlaybackOscillate: int = 2

# Utility constants
kDefaultTangentType: int = MFnAnimCurve.kTangentLinear
